# Run .test/ scripts and check output against commit
name: R2021a
on: # setup triggers
  push:
    paths: 
      - '**.m'    # diff in mfiles
  workflow_dispatch:  # manual-run
jobs:
  R2021a:
    uses: bellomia/colorlab/.github/workflows/CI.yaml@master
    with:
      release: R2021a